--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  creationTimestamp: ~
  labels: 
    app: rule-udr
  name: rule-udr
spec: 
  replicas: 3
  selector: 
    matchLabels: 
      app: rule-udr
  strategy: {}
  template: 
    metadata: 
      creationTimestamp: ~
      labels: 
        app: rule-udr
    spec: 
      containers: 
        - 
          env:
            - name: spring.data.elasticsearch.client.reactive.endpoints
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: SPRING_DATA_ELASTICSEARCH_CLIENT_REACTIVE_ENDPOINTS
            - name: spring.elasticsearch.rest.uris
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: SPRING_ELASTICSEARCH_REST_URIS
            - name: mdo.config.jwt_rsk
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: MDO_CONFIG_JWT_RSK
            - name: spring.rabbitmq.username
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: SPRING_RABBITMQ_USER
            - name: spring.rabbitmq.password
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: SPRING_RABBITMQ_PASSWD
            - name: spring.rabbitmq.addresses
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: SPRING_RABBITMQ_ADDRESS
            - name: spring.rabbitmq.host
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: SPRING_RABBITMQ_HOST
            - name: spring.rabbitmq.port
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: SPRING_RABBITMQ_PORT
            - name: server.canonical.url
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: SERVER_CANONICAL_URL_IN_UDR
            - name: server.name
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: SERVER_NAME
            - name: management.endpoint.health.show-details
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: MANAGEMENT_ENDPOINT_HEALTH_SHOW-DETAILS
            - name: management.health.defaults.enabled
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: MANAGEMENT_HEALTH_DEFAULTS_ENABLED
            - name: elastic.link
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: ELASTIC_LINK
            - name: elastic.username
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: ELASTIC_USERNAME
            - name: elastic.password
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: ELASTIC_PASSWORD
            - name: NEW_RELIC_APP_NAME
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: SERVER_CANONICAL_URL_IN_UDR
            - name: NEW_RELIC_LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: ocp-dev-secrets
                  key: NEWRELIC_LICENSE_KEY
            - name: elastic.protocol
              value: https
            - name: elastic.port
              value: '9200'
            - name: server.port
              value: '8080'
          image: "docker.prospecta.com/prospecta/test:ruleudr-2"
          name: rule-udr
          ports:
            - name: spring-port
              containerPort: 8080
              protocol: TCP
          resources: {}
      securityContext: {}
      imagePullSecrets:
        - name: nexus-image-pull
---
